import { Inter } from "next/font/google";
import "./globals.css";
import localFont from 'next/font/local'

const myfont = localFont({ src: '../../public/gallerymodern-webfont.woff2'})

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={myfont.className}>{children}</body>
    </html>
  );
}
